name: stripe2
version: 4.12.0
description: A simple Stripe API wrapper, that is meant to be used on the server.

environment:
  sdk: ^3.1.0
dependencies:
  crypto: ^3.0.0
  json_annotation: ^4.4.0
  meta: ^1.1.7
  logging: ^1.0.1
  dio: ^5.1.2
  http: ^1.0.0
dev_dependencies:
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  test: ^1.3.0
  mocktail: ^1.0.3
  lints: ^3.0.0
